### ISSUE TITLE
Demo failed to run

### ISSUE THREAD

**Issue by neciszhang** [dreamgaussian/dreamgaussian#69]
Hi, I am running [this demo](https://colab.research.google.com/drive/1sLpYmmLS209-e5eHgcuqdryFRRO6ZhFS?usp=sharing#scrollTo=ues7lyQNUH3Y), but an error is reported during training.
![image](https://github.com/dreamgaussian/dreamgaussian/assets/16221107/e4c1c83d-5e59-455a-aa67-e75c3dc7cc3d)

**Comment by perceptiveminds** [comment]
I'm getting the  same error:
`ValueError: clip_camera_projection/zero123.py as defined in 'model_index.json' does not exist in bennyguo/zero123-xl-diffusers and is not a module in 'diffusers/pipelines'.`

**Comment by perceptiveminds** [comment]
A short and dirty way to get it working anyway: comment out the particular piece of pipeline_utils.py in the diffusers module that is throwing the error, and put a _pass_ into it:

![pipeline_utils](https://github.com/dreamgaussian/dreamgaussian/assets/2305677/b18dcbdc-4005-45e9-b250-e4dda0e7f6d0)

You can restore the file when the problem is solved in the future.

**Comment by alekolo7** [comment]
Downgrading diffusers to 0.21.4 helps as well.

**Comment by neciszhang** [comment]
> Downgrading diffusers to 0.21.4 helps as well.

Thanks!

**Comment by ashawkey** [comment]
Thanks for reporting this, I have fixed diffusers version for a temporary fix.
